version: "3.8"

services:
  node-server:
    container_name: node-server
    restart: always
    build:
      context: ./app
    ports:
      - "5000:5000"

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /www/nginx-cache:/www/cache
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf