version: "3.8"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./images:/www/images
      - ./nginx.conf:/etc/nginx/conf.d/default.conf